/* jshint node: true,esversion: 9, -W014, -W033 */
/* eslint-disable new-cap */
'use strict'

module.exports = {
  accNotFound: 'accessory not found',
  brand: 'Meross',
  cfgDef: 'is not a valid number so using default of',
  cfgDup: 'will be ignored since another entry with this ID already exists',
  cfgIgn: 'is not configured correctly so ignoring',
  cfgIgnItem: 'has an invalid entry which will be ignored',
  cfgItem: 'Config entry',
  cfgLow: 'is set too low so increasing to',
  cfgRmv: 'is unused and can be removed',
  cfgQts: 'should not have quotes around its entry',
  complete: '✓ Setup complete',
  devAdd: 'has been added to Homebridge',
  devInit: 'initialised with id',
  devNoAttributes: 'no model or IP address configured',
  devNotAdd: 'could not be added to Homebridge as',
  devNotConf: 'could not be configured as',
  devNotInit: 'could not be initialised as',
  devNotRemove: 'could not be removed from Homebridge as',
  devRemove: 'has been removed from Homebridge',
  disabling: 'Disabling plugin',
  disablingCloud: 'Disabling cloud client as',
  hbVersionFail: 'Your version of Homebridge is too low - update to v1.3',
  httpRetry: 'Unable to reach Meross, retrying in 30 seconds',
  identify: 'identify button pressed',
  initialised: 'Plugin initialised. Setting up accessories...',
  initialising: 'Initialising plugin',
  logout: 'Meross session closed and logged out',
  missingCreds: 'credentials not supplied in config',
  missingData: 'user key, messageId, timestamp or sign has not been set',
  noResponse: 'no response received from Meross server',
  notAuth: 'not authenticated',
  notSupp: 'is currently not supported, do create a github issue https://git.io/JtfVC with info',
  pluginNotConf: 'Plugin has not been configured',
  sendMQTT: 'sending mqtt',
  sendPolling: 'sending poll request',
  sendUpdate: 'sending update'
}
