/* jshint node: true, esversion: 10, -W014, -W033 */
/* eslint-disable new-cap */
'use strict'

module.exports = {
  accNotFound: 'accessory not found',
  brand: 'Meross Technology',
  cfgDef: 'is not a valid number so using default of',
  cfgDup: 'will be ignored since another entry with this ID already exists',
  cfgIgn: 'is not configured correctly so ignoring',
  cfgIgnItem: 'has an invalid entry which will be ignored',
  cfgItem: 'Config entry',
  cfgLow: 'is set too low so increasing to',
  cfgMoveEntry: 'configuration entry should be moved to appropriate section in the UI',
  cfgRmv: 'is unused and can be removed',
  cfgQts: 'should not have quotes around its entry',
  complete: '✓ Setup complete',
  devAdd: 'has been added to Homebridge',
  devInit: 'initialised with id',
  devInitOpts: 'initialising with options',
  devNotAdd: 'could not be added to Homebridge as',
  devNotConf: 'could not be configured as',
  devNotInit: 'could not be initialised as',
  devNotRemove: 'could not be removed from Homebridge as',
  devRemove: 'has been removed from Homebridge',
  disabled: 'To change this, set disablePlugin to false',
  disabling: 'Disabling plugin',
  disablingCloud: 'Disabling cloud client as',
  hbVersionFail: 'Your version of Homebridge is too low - update to v1.3',
  httpRetry: 'Unable to reach Meross, retrying in 30 seconds',
  identify: 'identify button pressed',
  incMQTT: 'incoming mqtt',
  incPoll: 'incoming poll',
  initialised: 'Plugin initialised. Setting up accessories...',
  initialising: 'Initialising plugin',
  invalidDevices: 'invalid device list received',
  invalidResponse: 'invalid response received',
  invalidSubdevices: 'invalid subdevice list received',
  jsonInfo: 'json debug info',
  loginFail: 'login failed',
  logout: 'Meross session closed and logged out',
  merossKey: 'Meross Key',
  missingCreds: 'username and password not supplied in config',
  noCredentials: 'Neither of username and password nor user key has been configured',
  noHybridMode: 'cloud control is forced',
  noInitHKIgnore: 'not initialising cloud device as matched as HomeKit native model',
  noInitIgnore: 'not initialising cloud device as ignored or configured locally',
  noIP: 'no IP address provided for device',
  noResponse: 'no response received from Meross server',
  notAuth: 'not authenticated',
  notSupp: 'is not supported, do create a github issue https://bit.ly/hb-meross-issues with info',
  notSuppLocal: 'device does not support local control',
  noUserKey: 'user key has not been configured',
  pluginNotConf: 'Plugin has not been configured',
  refFailed: 'failed to refresh status as',
  repOffline: 'has been reported [offline]',
  repOnline: 'has been reported [online]',
  reqFail: 'request failed',
  reqFailed: 'failed to request status as',
  revertToCloud: 'reverting to cloud control as',
  sendFailed: 'sending update failed as',
  sendMQTT: 'sending mqtt',
  sendPolling: 'sending poll request',
  sendUpdate: 'sending update',
  sensorNoCloud: 'cloud connection is necessary for MSH300',
  sensorNoSubs: 'subdevice list not in correct format',
  timeout: 'the request timed out',
  zWelcome: [
    "Don't forget to ☆ this plugin on GitHub if you're finding it useful!",
    'Have a feature request? Visit http://bit.ly/hb-meross-issues to ask!',
    'Interested in sponsoring this plugin? https://github.com/sponsors/bwp91',
    'Join the Homebridge Discord community! https://discord.gg/bHjKNkN',
    'Thanks for using this plugin, I hope you find it helpful!',
    'This plugin has been made with ♥ by bwp91 from the UK!',
    'Check out my other Homebridge plugins! https://github.com/bwp91',
    'This plugin currently has a 3¼☆ rating on HOOBS! http://bit.ly/hb-meross-review',
    'Have time to give this plugin a review? http://bit.ly/hb-meross-review'
  ]
}
